### ISSUE TITLE
休眠唤醒后键盘无法使用！！只能重启

### ISSUE THREAD

**Issue by MengYilun** [Sosueyakiko/OpenCore_EFI-For-DELL-G5-5587#1]
感谢大佬的efi 让我顺利装上了黑苹果，目前我发现几个问题，1，开机的时候回报一个 OCS：NO schema for GraphicsInputMirroring at 2 index,context<AppleInput>! 但是可以进入系统。
2.休眠唤醒后键盘会失灵，无法使用。只能重启。
3.有线网卡没有驱动，我使用therosE2200Ethernet.kext成功驱动有线网卡。
再次感谢。

**Comment by MengYilun** [comment]
还有一个 触摸板没有弄好，我的设置里面显示找不到触摸板，高级手势不能用。但是触摸板有反应可以移动鼠标

**Comment by Sosueyakiko** [comment]
非常感谢！
键盘失灵请使用这个https://github.com/acidanthera/VoodooPS2/releases/  换成最新版就可以了
下次更新的时候我会记得加上有线网卡
触摸板我有时也会出现这个，但是是概率。如果是热重启导致没有触摸板功能的，请尝试冷重启，反之亦然。如果都无效，请尝试开机时插上电源。再不行我就没办法了（毕竟我也已经很久没有遇到了

**Comment by MengYilun** [comment]
感谢回复，触摸板的话我换成了ApplePS2SmartTouchPad.kext，部分手势有反应了。就是设置里面显示空白。键盘问题解决了。
